### ISSUE TITLE
Character Features

### ISSUE THREAD

**Issue by JameeKim** [JameeKim/The-Outer-Space-The-Astronaut#1]
Combat-related features are separated to #5

- [X] Character physics (collider, rigid body) (#14)
- [X] Character movement: `PlayerCharacterController` component (#14)
- [X] Apply sprites and animations if applicable (#16)
- [ ] Play sound when walking/running
