### ISSUE TITLE
Map Design

### ISSUE THREAD

**Issue by JameeKim** [JameeKim/The-Outer-Space-The-Astronaut#3]
- [X] Prepare and organize sprites (#12)
- [X] Create a tilemap (#12)
- [x] Place sprites into the tilemap following the level design (#12, #19, #33, #37, #42, #43) 
- [X] Apply physics colliders (#12)
- [x] Apply background sound (#44)
- ~Apply environment sounds~
