### ISSUE TITLE
Interactables

### ISSUE THREAD

**Issue by JameeKim** [JameeKim/The-Outer-Space-The-Astronaut#6]
- [X] Create `Interactable` component that fires a `UnityEvent` when in contact with the player character (#15)
- [ ] Create oxygen (skeleton by #15)
- [ ] Create caffeine (skeleton by #15)
- [X] Place items (#19)

Here are the steps to implement the functionalities of Oxygen and Caffeine.

1. In `CombatEntity` component, create public methods to increase current health, attack, and defense.
   - health: `InternalCurrentHealth = currentHealth + <value>;`
   - attack: `InternalCurrentAttack = currentAttack + <value>;`
   - defense: `InternalCurrentDefense = currentDefense + <value>;`
1. In the `OnConsume` methods of `Oxygen` and `Caffeince` monobehaviours, call the appropriate methods created above by first getting the `CombatEntity` component.
   ```csharp
   public void OnConsume(GameObject player)
   {
       CombatEntity combatEntity = player.GetComponent<CombatEntity>();
       // do stuff with combatEntity
   }
   ```
